<?php

declare(strict_types=1);

namespace App\Commands;

use App\Libraries\SchemaRepairService;
use App\Libraries\TenantConnection;
use CodeIgniter\CLI\BaseCommand;
use CodeIgniter\CLI\CLI;

/**
 * Write app/Database/Schema/tables.php from a fully migrated tenant database and validate models.
 *
 *   php spark schema:snapshot -tenant swasthe_testing
 */
class SchemaSnapshot extends BaseCommand
{
    protected $group       = 'Database';
    protected $name        = 'schema:snapshot';
    protected $description = 'Generate the self-healing schema snapshot from a fully migrated tenant DB.';
    protected $usage       = 'schema:snapshot -tenant <key>';
    protected $options     = ['-tenant' => 'Reference tenant key (must have all migrations applied)'];

    public function run(array $params)
    {
        $tenant = (string) (CLI::getOption('tenant') ?? '');
        if ($tenant !== '' && ! (new TenantConnection())->apply($tenant, 'cli')) {
            CLI::error('Could not connect to tenant ' . $tenant);

            return EXIT_ERROR;
        }

        $db = db_connect();

        $pending = $this->pendingMigrations($db);
        if ($pending !== []) {
            CLI::error('Reference DB `' . $db->getDatabase() . '` is missing migrations: ' . implode(', ', $pending));
            CLI::write('Run migrations on it first so the snapshot is complete.');

            return EXIT_ERROR;
        }

        $definitions = (new SchemaRepairService())->readDefinitions($db);

        $file = SchemaRepairService::SNAPSHOT_FILE;
        if (! is_dir(dirname($file))) {
            mkdir(dirname($file), 0775, true);
        }
        $php = "<?php\n\n// Generated by `php spark schema:snapshot` from `" . $db->getDatabase() . '` on ' . date('Y-m-d H:i')
            . ".\n// Used by SchemaRepairService to auto-create missing tables / columns / indexes. Do not edit by hand.\n\nreturn "
            . var_export($definitions, true) . ";\n";
        file_put_contents($file, $php);

        CLI::write(sprintf('Snapshot written: %d tables → %s', count($definitions), $file), 'green');
        $this->validateModels($definitions);

        return EXIT_SUCCESS;
    }

    /**
     * @return list<string>
     */
    protected function pendingMigrations($db): array
    {
        $files = glob(APPPATH . 'Database/Migrations/*.php') ?: [];
        $done  = array_column($db->table('migrations')->select('version')->get()->getResultArray(), 'version');
        $out   = [];
        foreach ($files as $f) {
            $version = substr(basename($f), 0, 17);
            if (! in_array($version, $done, true)) {
                $out[] = basename($f, '.php');
            }
        }

        return $out;
    }

    /**
     * Every model table must be in the snapshot (or defined inline) and every allowedField must exist.
     *
     * @param array<string, array{columns: array<string, string>}> $definitions
     */
    protected function validateModels(array $definitions): void
    {
        $problems = 0;
        foreach (glob(APPPATH . 'Models/*.php') ?: [] as $file) {
            $class = 'App\\Models\\' . basename($file, '.php');
            if (! class_exists($class)) {
                continue;
            }
            $ref   = new \ReflectionClass($class);
            if ($ref->isAbstract()) {
                continue;
            }
            $props  = $ref->getDefaultProperties();
            $table  = (string) ($props['table'] ?? '');
            $inline = $props['schemaColumns'] ?? [];
            $cols   = $definitions[$table]['columns'] ?? $inline;
            if ($table === '') {
                continue;
            }
            if ($cols === []) {
                CLI::write("  ! {$ref->getShortName()}: table `{$table}` not in snapshot and no inline schema", 'yellow');
                $problems++;

                continue;
            }
            $missing = array_diff((array) ($props['allowedFields'] ?? []), array_keys($cols));
            if ($missing !== []) {
                CLI::write("  ! {$ref->getShortName()}: allowedFields not in `{$table}`: " . implode(', ', $missing), 'yellow');
                $problems++;
            }
        }

        CLI::write($problems === 0 ? 'Model validation: all models match the schema.' : "Model validation: {$problems} problem(s) above.", $problems === 0 ? 'green' : 'yellow');
    }
}
