<?php

// Generated by `php spark schema:snapshot` from `elintom_reach` on 2026-10-07 06:42.
// Used by SchemaRepairService to auto-create missing tables / columns / indexes. Do not edit by hand.

return array (
  'activity_logs' => 
  array (
    'columns' => 
    array (
      'id' => 'int unsigned NOT NULL AUTO_INCREMENT',
      'user_id' => 'int unsigned DEFAULT NULL',
      'action' => 'varchar(100) COLLATE utf8mb4_general_ci NOT NULL',
      'module' => 'varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL',
      'description' => 'text COLLATE utf8mb4_general_ci',
      'ip_address' => 'varchar(45) COLLATE utf8mb4_general_ci DEFAULT NULL',
      'user_agent' => 'varchar(500) COLLATE utf8mb4_general_ci DEFAULT NULL',
      'metadata' => 'longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin',
      'created_at' => 'datetime DEFAULT NULL',
    ),
    'indexes' => 
    array (
      'PRIMARY' => 'PRIMARY KEY (`id`)',
      'user_id' => 'KEY `user_id` (`user_id`)',
      'action' => 'KEY `action` (`action`)',
      'module' => 'KEY `module` (`module`)',
      'created_at' => 'KEY `created_at` (`created_at`)',
    ),
    'options' => 'ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci',
  ),
  'ai_copilot_logs' => 
  array (
    'columns' => 
    array (
      'id' => 'int unsigned NOT NULL AUTO_INCREMENT',
      'user_id' => 'int unsigned DEFAULT NULL',
      'screen' => 'varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL',
      'page_url' => 'varchar(500) COLLATE utf8mb4_general_ci DEFAULT NULL',
      'prompt' => 'text COLLATE utf8mb4_general_ci',
      'reply' => 'mediumtext COLLATE utf8mb4_general_ci',
      'thinking' => 'text COLLATE utf8mb4_general_ci',
      'action_type' => 'varchar(50) COLLATE utf8mb4_general_ci DEFAULT NULL',
      'action_data' => 'text COLLATE utf8mb4_general_ci',
      'is_active' => 'tinyint(1) NOT NULL DEFAULT \'1\'',
      'is_deleted' => 'tinyint(1) NOT NULL DEFAULT \'0\'',
      'created_at' => 'datetime DEFAULT NULL',
      'updated_at' => 'datetime DEFAULT NULL',
    ),
    'indexes' => 
    array (
      'PRIMARY' => 'PRIMARY KEY (`id`)',
      'user_id_is_deleted' => 'KEY `user_id_is_deleted` (`user_id`,`is_deleted`)',
    ),
    'options' => 'ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci',
  ),
  'api_tokens' => 
  array (
    'columns' => 
    array (
      'id' => 'int unsigned NOT NULL AUTO_INCREMENT',
      'user_id' => 'int unsigned NOT NULL',
      'name' => 'varchar(150) COLLATE utf8mb4_general_ci NOT NULL',
      'token_hash' => 'varchar(191) COLLATE utf8mb4_general_ci NOT NULL',
      'abilities' => 'longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin',
      'last_used_at' => 'datetime DEFAULT NULL',
      'expires_at' => 'datetime DEFAULT NULL',
      'created_at' => 'datetime DEFAULT NULL',
      'updated_at' => 'datetime DEFAULT NULL',
    ),
    'indexes' => 
    array (
      'PRIMARY' => 'PRIMARY KEY (`id`)',
      'token_hash' => 'UNIQUE KEY `token_hash` (`token_hash`)',
      'user_id' => 'KEY `user_id` (`user_id`)',
      'expires_at' => 'KEY `expires_at` (`expires_at`)',
    ),
    'options' => 'ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci',
  ),
  'automation_delayed_jobs' => 
  array (
    'columns' => 
    array (
      'id' => 'int unsigned NOT NULL AUTO_INCREMENT',
      'automation_id' => 'int unsigned NOT NULL',
      'contact_id' => 'int unsigned DEFAULT NULL',
      'resume_rule_id' => 'int unsigned DEFAULT NULL',
      'context_json' => 'longtext COLLATE utf8mb4_general_ci',
      'run_at' => 'datetime NOT NULL',
      'status' => 'varchar(20) COLLATE utf8mb4_general_ci NOT NULL DEFAULT \'pending\'',
      'created_at' => 'datetime DEFAULT NULL',
      'updated_at' => 'datetime DEFAULT NULL',
    ),
    'indexes' => 
    array (
      'PRIMARY' => 'PRIMARY KEY (`id`)',
      'status_run_at' => 'KEY `status_run_at` (`status`,`run_at`)',
      'automation_id' => 'KEY `automation_id` (`automation_id`)',
    ),
    'options' => 'ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci',
  ),
  'automation_rules' => 
  array (
    'columns' => 
    array (
      'id' => 'int unsigned NOT NULL AUTO_INCREMENT',
      'automation_id' => 'int unsigned NOT NULL',
      'step_order' => 'int unsigned NOT NULL DEFAULT \'1\'',
      'rule_type' => 'enum(\'condition\',\'action\') COLLATE utf8mb4_general_ci NOT NULL DEFAULT \'action\'',
      'action_type' => 'varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL',
      'config' => 'longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin',
      'next_on_true' => 'int unsigned DEFAULT NULL',
      'next_on_false' => 'int unsigned DEFAULT NULL',
      'created_at' => 'datetime DEFAULT NULL',
      'updated_at' => 'datetime DEFAULT NULL',
    ),
    'indexes' => 
    array (
      'PRIMARY' => 'PRIMARY KEY (`id`)',
      'automation_id' => 'KEY `automation_id` (`automation_id`)',
      'step_order' => 'KEY `step_order` (`step_order`)',
      'rule_type' => 'KEY `rule_type` (`rule_type`)',
    ),
    'options' => 'ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci',
  ),
  'automations' => 
  array (
    'columns' => 
    array (
      'id' => 'int unsigned NOT NULL AUTO_INCREMENT',
      'name' => 'varchar(191) COLLATE utf8mb4_general_ci NOT NULL',
      'trigger_type' => 'varchar(100) COLLATE utf8mb4_general_ci NOT NULL',
      'trigger_config' => 'longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin',
      'flow_graph' => 'longtext COLLATE utf8mb4_general_ci',
      'is_active' => 'tinyint(1) NOT NULL DEFAULT \'1\'',
      'priority' => 'int NOT NULL DEFAULT \'5\'',
      'created_by' => 'int unsigned DEFAULT NULL',
      'created_at' => 'datetime DEFAULT NULL',
      'updated_at' => 'datetime DEFAULT NULL',
    ),
    'indexes' => 
    array (
      'PRIMARY' => 'PRIMARY KEY (`id`)',
      'trigger_type' => 'KEY `trigger_type` (`trigger_type`)',
      'is_active' => 'KEY `is_active` (`is_active`)',
      'priority' => 'KEY `priority` (`priority`)',
      'created_by' => 'KEY `created_by` (`created_by`)',
    ),
    'options' => 'ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci',
  ),
  'campaign_contacts' => 
  array (
    'columns' => 
    array (
      'id' => 'int unsigned NOT NULL AUTO_INCREMENT',
      'campaign_id' => 'int unsigned NOT NULL',
      'contact_id' => 'int unsigned NOT NULL',
      'status' => 'enum(\'pending\',\'queued\',\'sent\',\'delivered\',\'read\',\'failed\') COLLATE utf8mb4_general_ci NOT NULL DEFAULT \'pending\'',
      'wa_message_id' => 'varchar(191) COLLATE utf8mb4_general_ci DEFAULT NULL',
      'error_message' => 'text COLLATE utf8mb4_general_ci',
      'sent_at' => 'datetime DEFAULT NULL',
      'delivered_at' => 'datetime DEFAULT NULL',
      'read_at' => 'datetime DEFAULT NULL',
      'created_at' => 'datetime DEFAULT NULL',
      'updated_at' => 'datetime DEFAULT NULL',
    ),
    'indexes' => 
    array (
      'PRIMARY' => 'PRIMARY KEY (`id`)',
      'campaign_id_contact_id' => 'UNIQUE KEY `campaign_id_contact_id` (`campaign_id`,`contact_id`)',
      'campaign_id' => 'KEY `campaign_id` (`campaign_id`)',
      'contact_id' => 'KEY `contact_id` (`contact_id`)',
      'status' => 'KEY `status` (`status`)',
      'wa_message_id' => 'KEY `wa_message_id` (`wa_message_id`)',
    ),
    'options' => 'ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci',
  ),
  'campaigns' => 
  array (
    'columns' => 
    array (
      'id' => 'int unsigned NOT NULL AUTO_INCREMENT',
      'name' => 'varchar(191) COLLATE utf8mb4_general_ci NOT NULL',
      'template_id' => 'int unsigned DEFAULT NULL',
      'status' => 'enum(\'draft\',\'scheduled\',\'running\',\'paused\',\'completed\',\'cancelled\') COLLATE utf8mb4_general_ci NOT NULL DEFAULT \'draft\'',
      'message_type' => 'varchar(50) COLLATE utf8mb4_general_ci NOT NULL DEFAULT \'template\'',
      'payload' => 'longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin',
      'variables' => 'longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin',
      'scheduled_at' => 'datetime DEFAULT NULL',
      'started_at' => 'datetime DEFAULT NULL',
      'completed_at' => 'datetime DEFAULT NULL',
      'total_contacts' => 'int unsigned NOT NULL DEFAULT \'0\'',
      'sent_count' => 'int unsigned NOT NULL DEFAULT \'0\'',
      'delivered_count' => 'int unsigned NOT NULL DEFAULT \'0\'',
      'read_count' => 'int unsigned NOT NULL DEFAULT \'0\'',
      'failed_count' => 'int unsigned NOT NULL DEFAULT \'0\'',
      'reply_count' => 'int unsigned NOT NULL DEFAULT \'0\'',
      'created_by' => 'int unsigned DEFAULT NULL',
      'created_at' => 'datetime DEFAULT NULL',
      'updated_at' => 'datetime DEFAULT NULL',
    ),
    'indexes' => 
    array (
      'PRIMARY' => 'PRIMARY KEY (`id`)',
      'template_id' => 'KEY `template_id` (`template_id`)',
      'status' => 'KEY `status` (`status`)',
      'scheduled_at' => 'KEY `scheduled_at` (`scheduled_at`)',
      'created_by' => 'KEY `created_by` (`created_by`)',
    ),
    'options' => 'ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci',
  ),
  'contact_attributes' => 
  array (
    'columns' => 
    array (
      'id' => 'int unsigned NOT NULL AUTO_INCREMENT',
      'attr_key' => 'varchar(50) COLLATE utf8mb4_general_ci NOT NULL',
      'label' => 'varchar(100) COLLATE utf8mb4_general_ci NOT NULL',
      'type' => 'varchar(20) COLLATE utf8mb4_general_ci NOT NULL DEFAULT \'text\'',
      'options' => 'text COLLATE utf8mb4_general_ci',
      'default_value' => 'varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL',
      'created_at' => 'datetime DEFAULT NULL',
      'updated_at' => 'datetime DEFAULT NULL',
    ),
    'indexes' => 
    array (
      'PRIMARY' => 'PRIMARY KEY (`id`)',
      'attr_key' => 'UNIQUE KEY `attr_key` (`attr_key`)',
    ),
    'options' => 'ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci',
  ),
  'contact_tags' => 
  array (
    'columns' => 
    array (
      'contact_id' => 'int unsigned NOT NULL',
      'tag_id' => 'int unsigned NOT NULL',
    ),
    'indexes' => 
    array (
      'PRIMARY' => 'PRIMARY KEY (`contact_id`,`tag_id`)',
      'contact_tags_tag_id_foreign' => 'KEY `contact_tags_tag_id_foreign` (`tag_id`)',
    ),
    'options' => 'ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci',
  ),
  'contacts' => 
  array (
    'columns' => 
    array (
      'id' => 'int unsigned NOT NULL AUTO_INCREMENT',
      'channel' => 'varchar(20) COLLATE utf8mb4_general_ci NOT NULL DEFAULT \'whatsapp\'',
      'external_id' => 'varchar(191) COLLATE utf8mb4_general_ci DEFAULT NULL',
      'name' => 'varchar(150) COLLATE utf8mb4_general_ci DEFAULT NULL',
      'mobile' => 'varchar(30) COLLATE utf8mb4_general_ci DEFAULT NULL',
      'country' => 'varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL',
      'email' => 'varchar(191) COLLATE utf8mb4_general_ci DEFAULT NULL',
      'notes' => 'text COLLATE utf8mb4_general_ci',
      'status' => 'enum(\'active\',\'inactive\',\'blocked\') COLLATE utf8mb4_general_ci NOT NULL DEFAULT \'active\'',
      'last_message_at' => 'datetime DEFAULT NULL',
      'last_reply_at' => 'datetime DEFAULT NULL',
      'assigned_to' => 'int unsigned DEFAULT NULL',
      'birthday' => 'date DEFAULT NULL',
      'custom_fields' => 'longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin',
      'created_at' => 'datetime DEFAULT NULL',
      'updated_at' => 'datetime DEFAULT NULL',
      'deleted_at' => 'datetime DEFAULT NULL',
      'wa_opted_in' => 'tinyint(1) DEFAULT NULL',
      'wa_opt_in_source' => 'varchar(50) COLLATE utf8mb4_general_ci DEFAULT NULL',
      'wa_opt_in_at' => 'datetime DEFAULT NULL',
      'wa_opted_out' => 'tinyint(1) DEFAULT NULL',
      'wa_opt_out_at' => 'datetime DEFAULT NULL',
      'wa_suppress_reason' => 'varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL',
      'wa_consent_requested_at' => 'datetime DEFAULT NULL',
      'wa_opt_in' => 'tinyint(1) NOT NULL DEFAULT \'0\'',
      'wa_opted_out_at' => 'datetime DEFAULT NULL',
      'wa_suppressed_until' => 'datetime DEFAULT NULL',
    ),
    'indexes' => 
    array (
      'PRIMARY' => 'PRIMARY KEY (`id`)',
      'channel_external_id' => 'UNIQUE KEY `channel_external_id` (`channel`,`external_id`)',
      'status' => 'KEY `status` (`status`)',
      'assigned_to' => 'KEY `assigned_to` (`assigned_to`)',
      'last_message_at' => 'KEY `last_message_at` (`last_message_at`)',
      'deleted_at' => 'KEY `deleted_at` (`deleted_at`)',
      'channel' => 'KEY `channel` (`channel`)',
      'mobile' => 'KEY `mobile` (`mobile`)',
      'contacts_wa_opt_in_idx' => 'KEY `contacts_wa_opt_in_idx` (`wa_opt_in`)',
      'contacts_wa_opted_out_at_idx' => 'KEY `contacts_wa_opted_out_at_idx` (`wa_opted_out_at`)',
      'contacts_wa_suppressed_until_idx' => 'KEY `contacts_wa_suppressed_until_idx` (`wa_suppressed_until`)',
    ),
    'options' => 'ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci',
  ),
  'conversations' => 
  array (
    'columns' => 
    array (
      'id' => 'int unsigned NOT NULL AUTO_INCREMENT',
      'contact_id' => 'int unsigned NOT NULL',
      'channel' => 'varchar(20) COLLATE utf8mb4_general_ci NOT NULL DEFAULT \'whatsapp\'',
      'page_id' => 'varchar(64) COLLATE utf8mb4_general_ci DEFAULT NULL',
      'last_message_id' => 'int unsigned DEFAULT NULL',
      'unread_count' => 'int unsigned NOT NULL DEFAULT \'0\'',
      'assigned_to' => 'int unsigned DEFAULT NULL',
      'status' => 'varchar(32) COLLATE utf8mb4_general_ci NOT NULL DEFAULT \'open\'',
      'last_message_at' => 'datetime DEFAULT NULL',
      'frt_due_at' => 'datetime DEFAULT NULL',
      'intervened_at' => 'datetime DEFAULT NULL',
      'ctwa_referral' => 'varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL',
      'created_at' => 'datetime DEFAULT NULL',
      'updated_at' => 'datetime DEFAULT NULL',
    ),
    'indexes' => 
    array (
      'PRIMARY' => 'PRIMARY KEY (`id`)',
      'contact_id' => 'UNIQUE KEY `contact_id` (`contact_id`)',
      'contact_channel' => 'UNIQUE KEY `contact_channel` (`contact_id`,`channel`)',
      'last_message_id' => 'KEY `last_message_id` (`last_message_id`)',
      'assigned_to' => 'KEY `assigned_to` (`assigned_to`)',
      'status' => 'KEY `status` (`status`)',
      'last_message_at' => 'KEY `last_message_at` (`last_message_at`)',
      'channel' => 'KEY `channel` (`channel`)',
    ),
    'options' => 'ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci',
  ),
  'countries' => 
  array (
    'columns' => 
    array (
      'id' => 'int unsigned NOT NULL AUTO_INCREMENT',
      'iso2' => 'varchar(2) COLLATE utf8mb4_unicode_ci NOT NULL',
      'name' => 'varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL',
      'dial_code' => 'varchar(10) COLLATE utf8mb4_unicode_ci NOT NULL',
      'min_digits' => 'tinyint unsigned NOT NULL DEFAULT \'7\'',
      'max_digits' => 'tinyint unsigned NOT NULL DEFAULT \'15\'',
      'phone_digits' => 'tinyint unsigned NOT NULL DEFAULT \'10\'',
      'sort_order' => 'smallint unsigned NOT NULL DEFAULT \'100\'',
      'is_active' => 'tinyint(1) NOT NULL DEFAULT \'1\'',
      'is_deleted' => 'tinyint(1) NOT NULL DEFAULT \'0\'',
      'created_at' => 'datetime NOT NULL DEFAULT CURRENT_TIMESTAMP',
      'updated_at' => 'datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP',
    ),
    'indexes' => 
    array (
      'PRIMARY' => 'PRIMARY KEY (`id`)',
      'uk_countries_iso2' => 'UNIQUE KEY `uk_countries_iso2` (`iso2`)',
      'idx_countries_dial_code' => 'KEY `idx_countries_dial_code` (`dial_code`)',
      'idx_countries_active' => 'KEY `idx_countries_active` (`is_active`,`is_deleted`,`sort_order`)',
    ),
    'options' => 'ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci',
  ),
  'email_builders' => 
  array (
    'columns' => 
    array (
      'id' => 'int unsigned NOT NULL AUTO_INCREMENT',
      'name' => 'varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL',
      'subject' => 'varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL',
      'html_content' => 'longtext COLLATE utf8mb4_unicode_ci',
      'attachment_path' => 'varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL',
      'attachment_name' => 'varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL',
      'cheerio_builder_id' => 'varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL',
      'status' => 'enum(\'draft\',\'active\',\'archived\') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT \'draft\'',
      'created_by' => 'int unsigned DEFAULT NULL',
      'created_at' => 'datetime DEFAULT NULL',
      'updated_at' => 'datetime DEFAULT NULL',
    ),
    'indexes' => 
    array (
      'PRIMARY' => 'PRIMARY KEY (`id`)',
      'status' => 'KEY `status` (`status`)',
      'cheerio_builder_id' => 'KEY `cheerio_builder_id` (`cheerio_builder_id`)',
    ),
    'options' => 'ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci',
  ),
  'email_drip_steps' => 
  array (
    'columns' => 
    array (
      'id' => 'int unsigned NOT NULL AUTO_INCREMENT',
      'drip_id' => 'int unsigned NOT NULL',
      'step_order' => 'int NOT NULL DEFAULT \'1\'',
      'delay_hours' => 'int NOT NULL DEFAULT \'0\'',
      'subject' => 'varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL',
      'html_content' => 'longtext COLLATE utf8mb4_unicode_ci',
      'builder_id' => 'int unsigned DEFAULT NULL',
      'created_at' => 'datetime DEFAULT NULL',
      'updated_at' => 'datetime DEFAULT NULL',
    ),
    'indexes' => 
    array (
      'PRIMARY' => 'PRIMARY KEY (`id`)',
      'email_drip_steps_builder_id_foreign' => 'KEY `email_drip_steps_builder_id_foreign` (`builder_id`)',
      'drip_id_step_order' => 'KEY `drip_id_step_order` (`drip_id`,`step_order`)',
    ),
    'options' => 'ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci',
  ),
  'email_drips' => 
  array (
    'columns' => 
    array (
      'id' => 'int unsigned NOT NULL AUTO_INCREMENT',
      'name' => 'varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL',
      'description' => 'text COLLATE utf8mb4_unicode_ci',
      'trigger_type' => 'enum(\'manual\',\'on_subscribe\',\'on_tag\') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT \'manual\'',
      'trigger_value' => 'varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL',
      'status' => 'enum(\'draft\',\'active\',\'paused\',\'archived\') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT \'draft\'',
      'created_by' => 'int unsigned DEFAULT NULL',
      'created_at' => 'datetime DEFAULT NULL',
      'updated_at' => 'datetime DEFAULT NULL',
    ),
    'indexes' => 
    array (
      'PRIMARY' => 'PRIMARY KEY (`id`)',
      'status' => 'KEY `status` (`status`)',
    ),
    'options' => 'ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci',
  ),
  'email_html_campaigns' => 
  array (
    'columns' => 
    array (
      'id' => 'int unsigned NOT NULL AUTO_INCREMENT',
      'name' => 'varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL',
      'attachment_path' => 'varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL',
      'attachment_name' => 'varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL',
      'subject' => 'varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL',
      'html_content' => 'longtext COLLATE utf8mb4_unicode_ci',
      'builder_id' => 'int unsigned DEFAULT NULL',
      'cheerio_builder_id' => 'varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL',
      'sender_id' => 'int unsigned DEFAULT NULL',
      'mode' => 'enum(\'recipients\',\'label\') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT \'recipients\'',
      'label_name' => 'varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL',
      'recipients_json' => 'longtext COLLATE utf8mb4_unicode_ci',
      'status' => 'enum(\'draft\',\'queued\',\'sending\',\'sent\',\'failed\',\'cancelled\',\'paused\') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT \'draft\'',
      'sent_count' => 'int NOT NULL DEFAULT \'0\'',
      'failed_count' => 'int NOT NULL DEFAULT \'0\'',
      'last_error' => 'text COLLATE utf8mb4_unicode_ci',
      'sent_at' => 'datetime DEFAULT NULL',
      'scheduled_at' => 'datetime DEFAULT NULL',
      'created_by' => 'int unsigned DEFAULT NULL',
      'created_at' => 'datetime DEFAULT NULL',
      'updated_at' => 'datetime DEFAULT NULL',
    ),
    'indexes' => 
    array (
      'PRIMARY' => 'PRIMARY KEY (`id`)',
      'email_html_campaigns_builder_id_foreign' => 'KEY `email_html_campaigns_builder_id_foreign` (`builder_id`)',
      'status' => 'KEY `status` (`status`)',
    ),
    'options' => 'ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci',
  ),
  'email_logs' => 
  array (
    'columns' => 
    array (
      'id' => 'int unsigned NOT NULL AUTO_INCREMENT',
      'kind' => 'enum(\'single\',\'bulk\',\'campaign\',\'drip\',\'test\') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT \'single\'',
      'provider' => 'varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL',
      'to_email' => 'varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL',
      'subject' => 'varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL',
      'status' => 'enum(\'sent\',\'failed\',\'queued\') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT \'sent\'',
      'opened_at' => 'datetime DEFAULT NULL',
      'open_count' => 'int unsigned DEFAULT \'0\'',
      'clicked_at' => 'datetime DEFAULT NULL',
      'click_count' => 'int unsigned DEFAULT \'0\'',
      'first_opened_at' => 'datetime DEFAULT NULL',
      'campaign_id' => 'int unsigned DEFAULT NULL',
      'builder_id' => 'int unsigned DEFAULT NULL',
      'html_campaign_id' => 'int unsigned DEFAULT NULL',
      'drip_id' => 'int unsigned DEFAULT NULL',
      'message' => 'text COLLATE utf8mb4_unicode_ci',
      'meta_json' => 'text COLLATE utf8mb4_unicode_ci',
      'created_by' => 'int unsigned DEFAULT NULL',
      'created_at' => 'datetime DEFAULT NULL',
      'updated_at' => 'datetime DEFAULT NULL',
    ),
    'indexes' => 
    array (
      'PRIMARY' => 'PRIMARY KEY (`id`)',
      'status' => 'KEY `status` (`status`)',
      'kind' => 'KEY `kind` (`kind`)',
      'created_at' => 'KEY `created_at` (`created_at`)',
      'provider' => 'KEY `provider` (`provider`)',
    ),
    'options' => 'ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci',
  ),
  'email_recipient_events' => 
  array (
    'columns' => 
    array (
      'id' => 'int unsigned NOT NULL AUTO_INCREMENT',
      'log_id' => 'int unsigned NOT NULL DEFAULT \'0\'',
      'campaign_id' => 'int unsigned DEFAULT NULL',
      'email' => 'varchar(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL',
      'event_type' => 'varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL',
      'detail' => 'varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL',
      'message_id' => 'varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL',
      'event_count' => 'int unsigned NOT NULL DEFAULT \'1\'',
      'first_at' => 'datetime DEFAULT NULL',
      'last_at' => 'datetime DEFAULT NULL',
      'created_at' => 'datetime DEFAULT NULL',
      'updated_at' => 'datetime DEFAULT NULL',
    ),
    'indexes' => 
    array (
      'PRIMARY' => 'PRIMARY KEY (`id`)',
      'uniq_log_email_event' => 'UNIQUE KEY `uniq_log_email_event` (`log_id`,`email`,`event_type`)',
      'campaign_id' => 'KEY `campaign_id` (`campaign_id`)',
      'email_event_type' => 'KEY `email_event_type` (`email`,`event_type`)',
      'message_id' => 'KEY `message_id` (`message_id`)',
    ),
    'options' => 'ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci',
  ),
  'email_senders' => 
  array (
    'columns' => 
    array (
      'id' => 'int unsigned NOT NULL AUTO_INCREMENT',
      'type' => 'enum(\'sender\',\'domain\') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT \'sender\'',
      'purpose' => 'enum(\'transactional\',\'marketing\') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT \'transactional\'',
      'provider' => 'varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL',
      'name' => 'varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL',
      'email' => 'varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL',
      'domain' => 'varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL',
      'mail_from_domain' => 'varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL',
      'cheerio_id' => 'varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT \'External Cheerio Sender/Domain ID\'',
      'status' => 'enum(\'pending\',\'verified\',\'failed\',\'disabled\') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT \'pending\'',
      'dns_records' => 'text COLLATE utf8mb4_unicode_ci COMMENT \'JSON SPF/DKIM/DMARC notes\'',
      'notes' => 'text COLLATE utf8mb4_unicode_ci',
      'is_default' => 'tinyint(1) NOT NULL DEFAULT \'0\'',
      'last_checked_at' => 'datetime DEFAULT NULL',
      'created_at' => 'datetime DEFAULT NULL',
      'updated_at' => 'datetime DEFAULT NULL',
    ),
    'indexes' => 
    array (
      'PRIMARY' => 'PRIMARY KEY (`id`)',
      'type' => 'KEY `type` (`type`)',
      'status' => 'KEY `status` (`status`)',
    ),
    'options' => 'ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci',
  ),
  'email_unsubscribes' => 
  array (
    'columns' => 
    array (
      'id' => 'int unsigned NOT NULL AUTO_INCREMENT',
      'email' => 'varchar(191) COLLATE utf8mb4_general_ci NOT NULL',
      'campaign_id' => 'int unsigned DEFAULT NULL',
      'reason' => 'varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL',
      'ip_address' => 'varchar(45) COLLATE utf8mb4_general_ci DEFAULT NULL',
      'is_active' => 'tinyint(1) NOT NULL DEFAULT \'1\'',
      'is_deleted' => 'tinyint(1) NOT NULL DEFAULT \'0\'',
      'created_at' => 'datetime DEFAULT NULL',
      'updated_at' => 'datetime DEFAULT NULL',
    ),
    'indexes' => 
    array (
      'PRIMARY' => 'PRIMARY KEY (`id`)',
      'uniq_email' => 'UNIQUE KEY `uniq_email` (`email`)',
      'idx_campaign_id' => 'KEY `idx_campaign_id` (`campaign_id`)',
      'idx_is_deleted' => 'KEY `idx_is_deleted` (`is_deleted`)',
    ),
    'options' => 'ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci',
  ),
  'email_verifications' => 
  array (
    'columns' => 
    array (
      'id' => 'int unsigned NOT NULL AUTO_INCREMENT',
      'email' => 'varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL',
      'status' => 'enum(\'valid\',\'invalid\',\'risky\',\'unknown\') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT \'unknown\'',
      'syntax_ok' => 'tinyint(1) NOT NULL DEFAULT \'0\'',
      'mx_ok' => 'tinyint(1) NOT NULL DEFAULT \'0\'',
      'disposable' => 'tinyint(1) NOT NULL DEFAULT \'0\'',
      'checks_json' => 'text COLLATE utf8mb4_unicode_ci',
      'verified_at' => 'datetime DEFAULT NULL',
      'created_at' => 'datetime DEFAULT NULL',
      'updated_at' => 'datetime DEFAULT NULL',
    ),
    'indexes' => 
    array (
      'PRIMARY' => 'PRIMARY KEY (`id`)',
      'email' => 'KEY `email` (`email`)',
      'status' => 'KEY `status` (`status`)',
    ),
    'options' => 'ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci',
  ),
  'internal_notes' => 
  array (
    'columns' => 
    array (
      'id' => 'int unsigned NOT NULL AUTO_INCREMENT',
      'contact_id' => 'int unsigned NOT NULL',
      'user_id' => 'int unsigned NOT NULL',
      'note' => 'text COLLATE utf8mb4_general_ci NOT NULL',
      'is_internal' => 'tinyint(1) NOT NULL DEFAULT \'1\'',
      'created_at' => 'datetime DEFAULT NULL',
      'updated_at' => 'datetime DEFAULT NULL',
    ),
    'indexes' => 
    array (
      'PRIMARY' => 'PRIMARY KEY (`id`)',
      'contact_id' => 'KEY `contact_id` (`contact_id`)',
      'user_id' => 'KEY `user_id` (`user_id`)',
    ),
    'options' => 'ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci',
  ),
  'keywords' => 
  array (
    'columns' => 
    array (
      'id' => 'int unsigned NOT NULL AUTO_INCREMENT',
      'keyword' => 'varchar(191) COLLATE utf8mb4_general_ci NOT NULL',
      'match_type' => 'enum(\'exact\',\'contains\',\'starts_with\') COLLATE utf8mb4_general_ci NOT NULL DEFAULT \'exact\'',
      'response_type' => 'varchar(50) COLLATE utf8mb4_general_ci NOT NULL DEFAULT \'text\'',
      'response_content' => 'text COLLATE utf8mb4_general_ci',
      'response_payload' => 'longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin',
      'parent_id' => 'int unsigned DEFAULT NULL',
      'menu_order' => 'int NOT NULL DEFAULT \'0\'',
      'is_active' => 'tinyint(1) NOT NULL DEFAULT \'1\'',
      'created_at' => 'datetime DEFAULT NULL',
      'updated_at' => 'datetime DEFAULT NULL',
    ),
    'indexes' => 
    array (
      'PRIMARY' => 'PRIMARY KEY (`id`)',
      'keyword' => 'KEY `keyword` (`keyword`)',
      'match_type' => 'KEY `match_type` (`match_type`)',
      'parent_id' => 'KEY `parent_id` (`parent_id`)',
      'is_active' => 'KEY `is_active` (`is_active`)',
    ),
    'options' => 'ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci',
  ),
  'media' => 
  array (
    'columns' => 
    array (
      'id' => 'int unsigned NOT NULL AUTO_INCREMENT',
      'filename' => 'varchar(255) COLLATE utf8mb4_general_ci NOT NULL',
      'original_name' => 'varchar(255) COLLATE utf8mb4_general_ci NOT NULL',
      'mime_type' => 'varchar(100) COLLATE utf8mb4_general_ci NOT NULL',
      'size' => 'bigint unsigned NOT NULL DEFAULT \'0\'',
      'path' => 'varchar(500) COLLATE utf8mb4_general_ci NOT NULL',
      'wa_media_id' => 'varchar(191) COLLATE utf8mb4_general_ci DEFAULT NULL',
      'url' => 'varchar(500) COLLATE utf8mb4_general_ci DEFAULT NULL',
      'uploaded_by' => 'int unsigned DEFAULT NULL',
      'created_at' => 'datetime DEFAULT NULL',
      'updated_at' => 'datetime DEFAULT NULL',
    ),
    'indexes' => 
    array (
      'PRIMARY' => 'PRIMARY KEY (`id`)',
      'wa_media_id' => 'KEY `wa_media_id` (`wa_media_id`)',
      'uploaded_by' => 'KEY `uploaded_by` (`uploaded_by`)',
    ),
    'options' => 'ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci',
  ),
  'message_queue' => 
  array (
    'columns' => 
    array (
      'id' => 'int unsigned NOT NULL AUTO_INCREMENT',
      'campaign_id' => 'int unsigned DEFAULT NULL',
      'contact_id' => 'int unsigned NOT NULL',
      'message_type' => 'varchar(50) COLLATE utf8mb4_general_ci NOT NULL',
      'payload' => 'longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin',
      'priority' => 'int NOT NULL DEFAULT \'5\'',
      'status' => 'enum(\'pending\',\'processing\',\'sent\',\'failed\',\'cancelled\') COLLATE utf8mb4_general_ci NOT NULL DEFAULT \'pending\'',
      'attempts' => 'int unsigned NOT NULL DEFAULT \'0\'',
      'max_attempts' => 'int unsigned NOT NULL DEFAULT \'3\'',
      'scheduled_at' => 'datetime DEFAULT NULL',
      'processed_at' => 'datetime DEFAULT NULL',
      'wa_message_id' => 'varchar(191) COLLATE utf8mb4_general_ci DEFAULT NULL',
      'error_message' => 'text COLLATE utf8mb4_general_ci',
      'created_at' => 'datetime DEFAULT NULL',
      'updated_at' => 'datetime DEFAULT NULL',
    ),
    'indexes' => 
    array (
      'PRIMARY' => 'PRIMARY KEY (`id`)',
      'campaign_id' => 'KEY `campaign_id` (`campaign_id`)',
      'contact_id' => 'KEY `contact_id` (`contact_id`)',
      'status' => 'KEY `status` (`status`)',
      'priority' => 'KEY `priority` (`priority`)',
      'scheduled_at' => 'KEY `scheduled_at` (`scheduled_at`)',
    ),
    'options' => 'ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci',
  ),
  'message_sequences' => 
  array (
    'columns' => 
    array (
      'id' => 'int unsigned NOT NULL AUTO_INCREMENT',
      'name' => 'varchar(191) COLLATE utf8mb4_general_ci NOT NULL',
      'channel' => 'varchar(20) COLLATE utf8mb4_general_ci NOT NULL DEFAULT \'whatsapp\'',
      'is_active' => 'tinyint(1) NOT NULL DEFAULT \'1\'',
      'exit_on_reply' => 'tinyint(1) NOT NULL DEFAULT \'1\'',
      'created_by' => 'int unsigned DEFAULT NULL',
      'created_at' => 'datetime DEFAULT NULL',
      'updated_at' => 'datetime DEFAULT NULL',
    ),
    'indexes' => 
    array (
      'PRIMARY' => 'PRIMARY KEY (`id`)',
    ),
    'options' => 'ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci',
  ),
  'messages' => 
  array (
    'columns' => 
    array (
      'id' => 'int unsigned NOT NULL AUTO_INCREMENT',
      'contact_id' => 'int unsigned NOT NULL',
      'campaign_id' => 'int unsigned DEFAULT NULL',
      'direction' => 'enum(\'inbound\',\'outbound\') COLLATE utf8mb4_general_ci NOT NULL',
      'message_type' => 'varchar(50) COLLATE utf8mb4_general_ci NOT NULL DEFAULT \'text\'',
      'wa_message_id' => 'varchar(191) COLLATE utf8mb4_general_ci DEFAULT NULL',
      'wamid' => 'varchar(191) COLLATE utf8mb4_general_ci DEFAULT NULL',
      'external_message_id' => 'varchar(191) COLLATE utf8mb4_general_ci DEFAULT NULL',
      'content' => 'text COLLATE utf8mb4_general_ci',
      'media_url' => 'varchar(500) COLLATE utf8mb4_general_ci DEFAULT NULL',
      'media_id' => 'varchar(191) COLLATE utf8mb4_general_ci DEFAULT NULL',
      'payload' => 'longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin',
      'status' => 'enum(\'pending\',\'sent\',\'delivered\',\'read\',\'failed\',\'received\') COLLATE utf8mb4_general_ci NOT NULL DEFAULT \'pending\'',
      'error_code' => 'varchar(50) COLLATE utf8mb4_general_ci DEFAULT NULL',
      'error_message' => 'text COLLATE utf8mb4_general_ci',
      'is_read' => 'tinyint(1) NOT NULL DEFAULT \'0\'',
      'conversation_id' => 'int unsigned DEFAULT NULL',
      'channel' => 'varchar(20) COLLATE utf8mb4_general_ci NOT NULL DEFAULT \'whatsapp\'',
      'created_at' => 'datetime DEFAULT NULL',
      'updated_at' => 'datetime DEFAULT NULL',
      'wa_inbound_id' => 'varchar(191) COLLATE utf8mb4_general_ci GENERATED ALWAYS AS (if((`direction` = \'inbound\'),`wa_message_id`,NULL)) VIRTUAL',
    ),
    'indexes' => 
    array (
      'PRIMARY' => 'PRIMARY KEY (`id`)',
      'contact_id' => 'KEY `contact_id` (`contact_id`)',
      'campaign_id' => 'KEY `campaign_id` (`campaign_id`)',
      'direction' => 'KEY `direction` (`direction`)',
      'wa_message_id' => 'KEY `wa_message_id` (`wa_message_id`)',
      'wamid' => 'KEY `wamid` (`wamid`)',
      'status' => 'KEY `status` (`status`)',
      'conversation_id' => 'KEY `conversation_id` (`conversation_id`)',
      'created_at' => 'KEY `created_at` (`created_at`)',
      'channel' => 'KEY `channel` (`channel`)',
      'external_message_id' => 'KEY `external_message_id` (`external_message_id`)',
      'uniq_messages_wa_inbound_id' => 'UNIQUE KEY `uniq_messages_wa_inbound_id` (`wa_inbound_id`)',
    ),
    'options' => 'ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci',
  ),
  'notifications' => 
  array (
    'columns' => 
    array (
      'id' => 'int unsigned NOT NULL AUTO_INCREMENT',
      'user_id' => 'int unsigned NOT NULL',
      'title' => 'varchar(255) COLLATE utf8mb4_general_ci NOT NULL',
      'message' => 'text COLLATE utf8mb4_general_ci',
      'type' => 'varchar(50) COLLATE utf8mb4_general_ci NOT NULL DEFAULT \'info\'',
      'is_read' => 'tinyint(1) NOT NULL DEFAULT \'0\'',
      'link' => 'varchar(500) COLLATE utf8mb4_general_ci DEFAULT NULL',
      'created_at' => 'datetime DEFAULT NULL',
      'updated_at' => 'datetime DEFAULT NULL',
    ),
    'indexes' => 
    array (
      'PRIMARY' => 'PRIMARY KEY (`id`)',
      'user_id' => 'KEY `user_id` (`user_id`)',
      'is_read' => 'KEY `is_read` (`is_read`)',
      'type' => 'KEY `type` (`type`)',
    ),
    'options' => 'ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci',
  ),
  'password_resets' => 
  array (
    'columns' => 
    array (
      'email' => 'varchar(191) COLLATE utf8mb4_general_ci NOT NULL',
      'token' => 'varchar(255) COLLATE utf8mb4_general_ci NOT NULL',
      'created_at' => 'datetime DEFAULT NULL',
    ),
    'indexes' => 
    array (
      'email' => 'KEY `email` (`email`)',
      'token' => 'KEY `token` (`token`)',
    ),
    'options' => 'ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci',
  ),
  'permissions' => 
  array (
    'columns' => 
    array (
      'id' => 'int unsigned NOT NULL AUTO_INCREMENT',
      'name' => 'varchar(150) COLLATE utf8mb4_general_ci NOT NULL',
      'slug' => 'varchar(150) COLLATE utf8mb4_general_ci NOT NULL',
      'module' => 'varchar(100) COLLATE utf8mb4_general_ci NOT NULL',
      'description' => 'text COLLATE utf8mb4_general_ci',
      'created_at' => 'datetime DEFAULT NULL',
      'updated_at' => 'datetime DEFAULT NULL',
    ),
    'indexes' => 
    array (
      'PRIMARY' => 'PRIMARY KEY (`id`)',
      'slug' => 'UNIQUE KEY `slug` (`slug`)',
      'module' => 'KEY `module` (`module`)',
    ),
    'options' => 'ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci',
  ),
  'quick_replies' => 
  array (
    'columns' => 
    array (
      'id' => 'int unsigned NOT NULL AUTO_INCREMENT',
      'shortcut' => 'varchar(50) COLLATE utf8mb4_general_ci NOT NULL',
      'title' => 'varchar(100) COLLATE utf8mb4_general_ci NOT NULL',
      'message' => 'text COLLATE utf8mb4_general_ci NOT NULL',
      'created_by' => 'int unsigned DEFAULT NULL',
      'created_at' => 'datetime DEFAULT NULL',
      'updated_at' => 'datetime DEFAULT NULL',
    ),
    'indexes' => 
    array (
      'PRIMARY' => 'PRIMARY KEY (`id`)',
      'shortcut' => 'UNIQUE KEY `shortcut` (`shortcut`)',
    ),
    'options' => 'ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci',
  ),
  'rate_limits' => 
  array (
    'columns' => 
    array (
      'id' => 'int unsigned NOT NULL AUTO_INCREMENT',
      'key' => 'varchar(191) COLLATE utf8mb4_general_ci NOT NULL',
      'hits' => 'int unsigned NOT NULL DEFAULT \'0\'',
      'window_start' => 'datetime NOT NULL',
    ),
    'indexes' => 
    array (
      'PRIMARY' => 'PRIMARY KEY (`id`)',
      'key' => 'UNIQUE KEY `key` (`key`)',
      'window_start' => 'KEY `window_start` (`window_start`)',
    ),
    'options' => 'ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci',
  ),
  'role_permissions' => 
  array (
    'columns' => 
    array (
      'role_id' => 'int unsigned NOT NULL',
      'permission_id' => 'int unsigned NOT NULL',
    ),
    'indexes' => 
    array (
      'PRIMARY' => 'PRIMARY KEY (`role_id`,`permission_id`)',
      'role_permissions_permission_id_foreign' => 'KEY `role_permissions_permission_id_foreign` (`permission_id`)',
    ),
    'options' => 'ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci',
  ),
  'roles' => 
  array (
    'columns' => 
    array (
      'id' => 'int unsigned NOT NULL AUTO_INCREMENT',
      'name' => 'varchar(100) COLLATE utf8mb4_general_ci NOT NULL',
      'slug' => 'varchar(100) COLLATE utf8mb4_general_ci NOT NULL',
      'description' => 'text COLLATE utf8mb4_general_ci',
      'created_at' => 'datetime DEFAULT NULL',
      'updated_at' => 'datetime DEFAULT NULL',
    ),
    'indexes' => 
    array (
      'PRIMARY' => 'PRIMARY KEY (`id`)',
      'name' => 'UNIQUE KEY `name` (`name`)',
      'slug' => 'UNIQUE KEY `slug` (`slug`)',
    ),
    'options' => 'ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci',
  ),
  'sequence_enrollments' => 
  array (
    'columns' => 
    array (
      'id' => 'int unsigned NOT NULL AUTO_INCREMENT',
      'sequence_id' => 'int unsigned NOT NULL',
      'contact_id' => 'int unsigned NOT NULL',
      'current_step' => 'int unsigned NOT NULL DEFAULT \'0\'',
      'status' => 'varchar(20) COLLATE utf8mb4_general_ci NOT NULL DEFAULT \'active\'',
      'next_run_at' => 'datetime DEFAULT NULL',
      'last_sent_at' => 'datetime DEFAULT NULL',
      'created_at' => 'datetime DEFAULT NULL',
      'updated_at' => 'datetime DEFAULT NULL',
    ),
    'indexes' => 
    array (
      'PRIMARY' => 'PRIMARY KEY (`id`)',
      'sequence_id_contact_id' => 'UNIQUE KEY `sequence_id_contact_id` (`sequence_id`,`contact_id`)',
      'status_next_run_at' => 'KEY `status_next_run_at` (`status`,`next_run_at`)',
    ),
    'options' => 'ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci',
  ),
  'sequence_steps' => 
  array (
    'columns' => 
    array (
      'id' => 'int unsigned NOT NULL AUTO_INCREMENT',
      'sequence_id' => 'int unsigned NOT NULL',
      'step_order' => 'int unsigned NOT NULL DEFAULT \'1\'',
      'delay_minutes' => 'int unsigned NOT NULL DEFAULT \'0\'',
      'message_type' => 'varchar(30) COLLATE utf8mb4_general_ci NOT NULL DEFAULT \'text\'',
      'template_name' => 'varchar(191) COLLATE utf8mb4_general_ci DEFAULT NULL',
      'language' => 'varchar(20) COLLATE utf8mb4_general_ci NOT NULL DEFAULT \'en\'',
      'body_text' => 'text COLLATE utf8mb4_general_ci',
      'created_at' => 'datetime DEFAULT NULL',
      'updated_at' => 'datetime DEFAULT NULL',
    ),
    'indexes' => 
    array (
      'PRIMARY' => 'PRIMARY KEY (`id`)',
      'sequence_id_step_order' => 'KEY `sequence_id_step_order` (`sequence_id`,`step_order`)',
    ),
    'options' => 'ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci',
  ),
  'settings' => 
  array (
    'columns' => 
    array (
      'id' => 'int unsigned NOT NULL AUTO_INCREMENT',
      'key' => 'varchar(191) COLLATE utf8mb4_general_ci NOT NULL',
      'value' => 'text COLLATE utf8mb4_general_ci',
      'group' => 'varchar(100) COLLATE utf8mb4_general_ci NOT NULL DEFAULT \'general\'',
      'is_encrypted' => 'tinyint(1) NOT NULL DEFAULT \'0\'',
      'created_at' => 'datetime DEFAULT NULL',
      'updated_at' => 'datetime DEFAULT NULL',
    ),
    'indexes' => 
    array (
      'PRIMARY' => 'PRIMARY KEY (`id`)',
      'key' => 'UNIQUE KEY `key` (`key`)',
      'group' => 'KEY `group` (`group`)',
    ),
    'options' => 'ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci',
  ),
  'tags' => 
  array (
    'columns' => 
    array (
      'id' => 'int unsigned NOT NULL AUTO_INCREMENT',
      'name' => 'varchar(100) COLLATE utf8mb4_general_ci NOT NULL',
      'color' => 'varchar(20) COLLATE utf8mb4_general_ci NOT NULL DEFAULT \'#6B7280\'',
      'created_at' => 'datetime DEFAULT NULL',
      'updated_at' => 'datetime DEFAULT NULL',
    ),
    'indexes' => 
    array (
      'PRIMARY' => 'PRIMARY KEY (`id`)',
      'name' => 'UNIQUE KEY `name` (`name`)',
    ),
    'options' => 'ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci',
  ),
  'templates' => 
  array (
    'columns' => 
    array (
      'id' => 'int unsigned NOT NULL AUTO_INCREMENT',
      'waba_id' => 'varchar(64) COLLATE utf8mb4_general_ci DEFAULT NULL',
      'meta_id' => 'varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL',
      'name' => 'varchar(191) COLLATE utf8mb4_general_ci NOT NULL',
      'language' => 'varchar(20) COLLATE utf8mb4_general_ci NOT NULL DEFAULT \'en\'',
      'category' => 'varchar(50) COLLATE utf8mb4_general_ci DEFAULT NULL',
      'template_type' => 'varchar(30) COLLATE utf8mb4_general_ci DEFAULT \'default\'',
      'status' => 'varchar(50) COLLATE utf8mb4_general_ci NOT NULL DEFAULT \'PENDING\'',
      'rejected_reason' => 'text COLLATE utf8mb4_general_ci',
      'header_type' => 'varchar(30) COLLATE utf8mb4_general_ci DEFAULT NULL',
      'header_content' => 'text COLLATE utf8mb4_general_ci',
      'body' => 'text COLLATE utf8mb4_general_ci',
      'footer' => 'text COLLATE utf8mb4_general_ci',
      'buttons' => 'longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin',
      'variables' => 'longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin',
      'raw_payload' => 'longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin',
      'synced_at' => 'datetime DEFAULT NULL',
      'created_at' => 'datetime DEFAULT NULL',
      'updated_at' => 'datetime DEFAULT NULL',
    ),
    'indexes' => 
    array (
      'PRIMARY' => 'PRIMARY KEY (`id`)',
      'templates_waba_meta_unique' => 'UNIQUE KEY `templates_waba_meta_unique` (`waba_id`,`meta_id`)',
      'templates_waba_name_lang_unique' => 'UNIQUE KEY `templates_waba_name_lang_unique` (`waba_id`,`name`,`language`)',
      'meta_id' => 'KEY `meta_id` (`meta_id`)',
      'name' => 'KEY `name` (`name`)',
      'status' => 'KEY `status` (`status`)',
      'templates_waba_id_idx' => 'KEY `templates_waba_id_idx` (`waba_id`)',
    ),
    'options' => 'ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci',
  ),
  'users' => 
  array (
    'columns' => 
    array (
      'id' => 'int unsigned NOT NULL AUTO_INCREMENT',
      'role_id' => 'int unsigned NOT NULL',
      'name' => 'varchar(150) COLLATE utf8mb4_general_ci NOT NULL',
      'email' => 'varchar(191) COLLATE utf8mb4_general_ci NOT NULL',
      'password' => 'varchar(255) COLLATE utf8mb4_general_ci NOT NULL',
      'email_verification_token' => 'varchar(64) COLLATE utf8mb4_general_ci DEFAULT NULL',
      'email_verification_sent_at' => 'datetime DEFAULT NULL',
      'email_verified_at' => 'datetime DEFAULT NULL',
      'phone' => 'varchar(30) COLLATE utf8mb4_general_ci DEFAULT NULL',
      'avatar' => 'varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL',
      'status' => 'enum(\'active\',\'inactive\') COLLATE utf8mb4_general_ci NOT NULL DEFAULT \'active\'',
      'last_login' => 'datetime DEFAULT NULL',
      'remember_token' => 'varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL',
      'created_at' => 'datetime DEFAULT NULL',
      'updated_at' => 'datetime DEFAULT NULL',
      'deleted_at' => 'datetime DEFAULT NULL',
    ),
    'indexes' => 
    array (
      'PRIMARY' => 'PRIMARY KEY (`id`)',
      'email' => 'UNIQUE KEY `email` (`email`)',
      'users_email_verification_token_unique' => 'UNIQUE KEY `users_email_verification_token_unique` (`email_verification_token`)',
      'role_id' => 'KEY `role_id` (`role_id`)',
      'status' => 'KEY `status` (`status`)',
      'deleted_at' => 'KEY `deleted_at` (`deleted_at`)',
      'users_email_verified_at_index' => 'KEY `users_email_verified_at_index` (`email_verified_at`)',
    ),
    'options' => 'ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci',
  ),
  'webhook_logs' => 
  array (
    'columns' => 
    array (
      'id' => 'int unsigned NOT NULL AUTO_INCREMENT',
      'event_type' => 'varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL',
      'payload' => 'longtext COLLATE utf8mb4_general_ci',
      'headers' => 'longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin',
      'signature_valid' => 'tinyint(1) NOT NULL DEFAULT \'0\'',
      'processed' => 'tinyint(1) NOT NULL DEFAULT \'0\'',
      'error_message' => 'text COLLATE utf8mb4_general_ci',
      'created_at' => 'datetime DEFAULT NULL',
    ),
    'indexes' => 
    array (
      'PRIMARY' => 'PRIMARY KEY (`id`)',
      'event_type' => 'KEY `event_type` (`event_type`)',
      'processed' => 'KEY `processed` (`processed`)',
      'created_at' => 'KEY `created_at` (`created_at`)',
    ),
    'options' => 'ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci',
  ),
);
